### ISSUE TITLE
Setup GitHub Actions CI against a Lotus devnet

### ISSUE THREAD

**Issue by raulk** [filecoin-project/fevm-contract-tests#1]
## Goal

Run all the test cases defined here in an embedded Lotus devnet. For now, it's sufficient to:

1. Set up a timer-based CI running every 4 hours.
2. Against specific branches of Lotus configured in the CI config.

To set up the devnet, I would use the itests framework. We should be able to set up a go command that uses the itests framework to spin up an "embedded Lotus devnet" with an arbitrary block time.

## Embedded Lotus devnet

1. Create a Go program that sets up an [itests ensemble](https://github.com/filecoin-project/lotus/blob/feat/nv18-fevm/itests/eth_deploy_test.go), makes it run to infinity, and sets up an HTTP endpoint for control on a designated localhost port (e.g. 1111).
2. The HTTP endpoint would have three commands:
	- http://localhost:1111/ready => returns when the ensemble is setup
	- http://localhost:1111/urls => returns the URLs of the daemon and the miner endpoints
	- http://localhost:1111/kill => kills the ensemble by exiting the process

## CI job

1. Spin up the go program in the background.
2. Call `ready` and wait until it returns an HTTP 200 OK.
3. Call `urls` to get the URLs to interact with the ensemble, so we can set up the tests.
4. Run the tests.
5. When the tests are done, call `kill`.

## Considerations

- Wallet => tests may need the private keys of Ethereum accounts that have been prefunded. The ensemble is already set up with a default wallet account, so maybe the CI scripts need to send funds to f410 accounts and then seed them through env variables to the tests.

**Comment by ychiaoli18** [comment]
@raulk Instead of having a long-running lotus node, it's cleaner to have each integration test file launch its lotus node in the test setup and kill the node when the test ends. How do you think?
